### ISSUE TITLE
Compiled ES5 version

### ISSUE THREAD

**Issue by gaearon** [r3dm/warning#1]
Hi, can you please publish a compiled ES5 version? It's generally more convenient (and performant) to not have to apply transforms to `node_modules`.

**Comment by BerkeleyTrue** [comment]
Geez, didn't realize I missed the arrow function. Will correct. See any other spots I missed?

**Comment by gaearon** [comment]
Looks good to me. I'd probably drop `Welcome to debug React` to avoid confusion but maybe not.

**Comment by BerkeleyTrue** [comment]
I went ahead and removed that line.
