### ISSUE TITLE
Can you consider add colors for cli users ?

### ISSUE THREAD

**Issue by jianghai** [r3dm/warning#10]

**Comment by BerkeleyTrue** [comment]
This is a mirror of Facebook's warning. As such the code here will match as close as possible.

[here](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/__forks__/warning.js) is their current implementation.

I suggest creating an issue with Facebook [here](https://github.com/facebook/fbjs/issues).

Happy Coding
