### ISSUE TITLE
Update license to MIT

### ISSUE THREAD

**Issue by Emeegeemee** [r3dm/warning#16]
Would it be possible to update the repo to include the new MIT license as seen in the fbjs repo?

**Comment by BerkeleyTrue** [comment]
Yes, if the fbjs repo is now MIT, so should this be. Mind submitting a PR?

**Comment by Emeegeemee** [comment]
I'll give it a shot.

**Comment by Emeegeemee** [comment]
PR #17 updates warning.js and browser.js to use the latest version from fbjs. I also switched everything to use es5 since looking through the repo history that was done previously.
