### ISSUE TITLE
Use `console.warn`?

### ISSUE THREAD

**Issue by mxdubois** [r3dm/warning#3]
I would expect this library to use `console.warn` instead of `console.error`.

When an invariant is violated, the application is in a broken state, so an error is appropriate. But I would assume this library is for notifying developers that they might have made a non-fatal mistake -- perhaps they used a deprecated function, or omitted some environment variables that are only required in production.

**Comment by BerkeleyTrue** [comment]
Hello @mxdubois 

This is a mirror of Facebooks warning. As such the code here will match as close as possible. They use console.error, I use console.error.

[here](https://github.com/facebook/fbjs/blob/32d47ebfa73ffdc6e5bdcd2be224ab81bc705a36/src/__forks__/warning.js) is their current implementation.

I suggest creating an issue with facebook [here](https://github.com/facebook/fbjs/issues).

Have a fantastic day!

**Comment by mxdubois** [comment]
Hm. Fair enough. Thanks.

**Comment by sean-clayton** [comment]
I made a pull request that will make Facebook's warning.js use `console.warn` instead of `console.error`. Pull request status here: facebook/fbjs#94

In the event it is merged, could we revisit this issue?

**Comment by BerkeleyTrue** [comment]
Sure. But seeing how FB [purposefully](https://github.com/facebook/react/commit/e791fccf5833450fff2929416174d489b9785e37) switched to console.error to show stack traces, I highly doubt it will be merged.
