### ISSUE TITLE
Printing stack trace in node

### ISSUE THREAD

**Issue by parshap** [r3dm/warning#6]
What do you  think about using `console.trace` instead of `console.error` in node to get a stack trace? `console.error` provides a stack trace in browsers, but not in node.

**Comment by BerkeleyTrue** [comment]
A lot of projects depend on this project being as close as possible to the functionality of FaceBooks warning. 

I don't think it's a good idea to deviate from FaceBooks original module.

I'll leave this open for now and see what the community thinks but you should petition FaceBook on their project source.

**Comment by BerkeleyTrue** [comment]
Closing.
