### ISSUE TITLE
Don't display anything for TEST environment?

### ISSUE THREAD

**Issue by danielkcz** [r3dm/warning#7]
I know this comes from Facebook, but it's somewhat annoying to see bunch of warnings during tests which don't always make proper calls to test stuff. Would be possible to add condition for `NODE_ENV === 'test'`?

**Comment by BerkeleyTrue** [comment]
This is just a mirror of Facebook's warning module. As such, we won't be changing behavior here. 

Happy Coding!

**Comment by danielkcz** [comment]
Ok I expected as much, I made my own fork for that. So if anyone is interested and want to avoid warnings during tests, just go with `npm install github:BlackDice/warning`.
