### ISSUE TITLE
Please clearify license

### ISSUE THREAD

**Issue by leipert** [r3dm/warning#8]
According to your `package.json`, this project is licensed under BSD-2-Clause.
The `LICENSE.md` contains the text of BSD-3-Clause.

Under which License is it licensed?

**Comment by BerkeleyTrue** [comment]
@leipert Thanks for bringing this to my attention, seems like the license is BSD-3-Clause according to https://github.com/facebook/fbjs/blob/89ffda59d923183dd34efb2622da0176ccb04d41/package.json. May have been a typo on my part.

Care to submit a PR updating the package.json?
